# Generated by Django 4.1.1 on 2022-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('subjectmatter', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
